AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A small description of the template
Resources:
  LambdaApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: TestLambdaApi
      StageName: Develop
  MyLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://orestis-b1/8c05c36d03521be55f6074b9597909e3
      Runtime: java11
      Handler: lambda.LambdaHandler::handleRequest
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
      Events:
        LambdaApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId:
              Ref: LambdaApi
