AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: "A small description of the template"

Resources:
  LambdaApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: develop
      Cors: "'*'"

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: LambdaAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

  MyLambda:
    DependsOn: LambdaRole
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Runtime: java11
      Handler: lambda.LambdaHandler::handleRequest
      Role: !GetAtt LambdaRole.Arn
      MemorySize: 1400
      Timeout: 60
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
      Events:
          LambdaApi:
            Type: Api
            Properties:
              Path: /hello/
              Method: get
              RestApiId: !Ref LambdaApi